title: "Introduccion a GitHub"
description: Si estás buscando una introducción a GitHub fácil y divertida, la has encontrado. Este curso te pondrá en marcha con GitHub en menos de una hora.
template:
  name: presentacion-github
  repo: intro-github-plantilla
  description: 'Un repositorio de entrenamiento, gestionado por un robot :robot:'
preferences:
- type: radio
  name: gitTool
  label: Herramienta Git preferida
  description: Aprende directamente desde la interfaz web, o utiliza tu herramienta preferida
  options:
  - label: Usa Visual Studio Code
    value: vscode
  - label: Usa la interfaz web de GitHub.com
    value: dotcom
    selected: true
  - label: Usa la línea de comandos
    value: cli
before:
- type: updateBranchProtection
- type: createIssue
  title: Getting Started with GitHub
  body: 00_introduction.md
  comments:
    - 00_assign-yourself.md

# Course artifacts:
#   1. Issue: Getting started with GitHub
#   2. Issue: Your first contribution
#   3. PR: [Created by learner]

steps:

# 1
- title: Asígnate
  description: Asígnate la primera propuesta. 
  event: issues.assigned
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: gate
    left: '%payload.assignee.login%'
    operator: ===
    right: '%user.username%'
  - type: respond
    with: 01_turn-on-gh-pages.md

# 2
- title: Activa GitHub Pages
  description: Activa GitHub Pages en la página de configuración del repositorio. 
  event: page_build
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: octokit
    method: repos.getPages
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    store:
      pagesUrl: '{{ result.data.html_url }}'
    action_id: pagesUrl
  - type: respond
    issue: Getting Started with GitHub
    with: 02_close-issue.md

# 3
- title: Cierra una propuesta
  description: Termina una conversación al cerrar una propuesta. 
  event: issues.closed
  link: '{{ repoUrl }}/issues/1'
  actions:
  - type: createIssue
    action_id: contrib_issue
    title: Your first contribution
    body: 03_your-first-contribution.md
    comments:
      - 03_create-a-branch.md
    data:
      thePayload: '%payload%'
  - type: respond
    with: 03_head-to-branch.md
    data:
      issueURL: '%actions.contrib_issue.data.html_url%'

# 4
- title: Crea una rama
  description: Crea una rama para introducir nuevos cambios. 
  event: create
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: respond
    issue: Your first contribution
    with: 04_commit-something.md
    data:
      thePayload: '%payload%'

# 5
- title: Confirma un archivo
  description: Confirma un archivo a tu rama. 
  event: push
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: respond
    issue: Your first contribution
    with: 05_open-a-pr.md
    data:
      branch: '%payload.ref%'
      url: '%payload.repository.html_url%/compare/%payload.ref%?expand=1'

# 6
- title: Abre una solicitud de extracción
  description: Abre una solicitud de extracción para proponer agregar tu nuevo archivo al proyecto.
  event: pull_request
  link: '{{ repoUrl }}/issues/2'
  actions:
  - type: gate
    gates:
    - left: '%payload.action%'
      operator: ===
      right: opened
    - left: '%payload.action%'
      operator: ===
      right: edited
    - left: '%payload.action%'
      operator: ===
      right: synchronize
  - type: closeIssue
    issue: Your first contribution
  - type: gate
    left: '%payload.pull_request.body%'
    else: 
    - type: createReview
      body: 06_fix-body.md
      event: REQUEST_CHANGES
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: master
    else:
    - type: createReview
      body: 06_fix-base.md
      event: REQUEST_CHANGES
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:/_posts\/\d{4}-\d{2}-\d{2}-%user.username%\.md/
    else:
    - type: createReview
      body: 06_fix-filename.md
      event: REQUEST_CHANGES
      data:
        expected: _posts/0000-01-02-%user.username%.md
        url: '%payload.pull_request.html_url%/files'
  - type: createReview
    body: 06_request-changes.md
    event: 'COMMENT'
    data:
      branch: '%payload.pull_request.head.ref%'
      url: '%payload.pull_request.html_url%/files'

# 7
- title: Responde a una revisión
  description: Responde a una revisión en tu solicitud de extracción.
  event: pull_request.synchronize
  link: '{{ repoUrl }}/pull/3'
  actions:
  - type: removeBranchProtection
  - type: createReview
    body: 07_pr-succeeds.md
    event: APPROVE
    data:
      branch: '%payload.pull_request.head.ref%'

# 8
- title: Fusiona tu solicitud de extracción
  description: Publica tus cambios al fusionar tu solicitud de extracción.
  event: pull_request.closed
  link: '{{ repoUrl }}/pull/3'
  actions:
  - type: gate
    left: '%payload.pull_request.merged%'
    else:
      - type: respond
        with: 08_reopen.md
  - type: respond
    with: 08_reminder-delete.md

tags: [
  "Git","GitHub Pages","Branches","Commits","Pull Requests"
]
video: "sz6zfrQpCQg"
